services:
  - type: web
    name: mcrew-design-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: 8363446053:AAGfig_At866R3bVU9rNrY4AOuJQxnz_t2M
      - key: ADMIN_USERNAME
        value: mcrewdm
      - key: YOUR_USERNAME
        value: mcrewdm
      - key: PORTFOLIO_CHANNEL
        value: "@mindescrew"